### ISSUE TITLE
I need ur help

### ISSUE THREAD

**Issue by erLCoder** [OpsecGuy/BetterGo#11]
Dude, can u explain me please how to do glow with new update, i tried to check ur code but i dont have a lot info about structs. If u can just DM in discord please erL#7734

**Comment by erLCoder** [comment]
Is this string "var = list(struct.unpack("2i4f4c3f4c3i", bytes))" static after updates, I just trying to get it. 2i4f4c3f4c3i staying static after update or dynamic and if its is dynamic. How i can find it out?

**Comment by erLCoder** [comment]
Is this string "var = list(struct.unpack("2i4f4c3f4c3i", bytes))" static after updates, I just trying to get it. 2i4f4c3f4c3i staying static after update or dynamic and if its is dynamic. How i can find it out?

**Comment by erLCoder** [comment]
Is this string "var = list(struct.unpack("2i4f4c3f4c3i", bytes))" static after updates, I just trying to get it. 2i4f4c3f4c3i staying static after update or dynamic and if its is dynamic. How i can find it out?

**Comment by OpsecGuy** [comment]
This variable 'VAR' unpack glow object definition. it gonna be static as long as this structure does not change .
var[1]
var[2]... 
Represents position in structure

https://i.imgur.com/zXS6bfm.png

**Comment by erLCoder** [comment]
thank u)
