### ISSUE TITLE
HELP!  What does 40 and ENTITY[2] mean?

### ISSUE THREAD

**Issue by mawangdan** [OpsecGuy/BetterGo#12]
https://github.com/OpsecGuy/BetterGo/blob/d6792655db57fd8e0437d432b9e68577900e3b25/app.py#L106

**Comment by mawangdan** [comment]
Any document?

**Comment by OpsecGuy** [comment]
Hey,

as you can see in entity.py there is a line with:
self.entity_list.append([i, entity, self.class_id(entity)])

which stores values in entity_list array. Example:  [1, 324232131, 50]
so whenever you call entity you need to specify what exactly do you want to take from the list (index, entity address, class id).

**Comment by mawangdan** [comment]
> Hey,
> 
> as you can see in entity.py there is a line with: self.entity_list.append([i, entity, self.class_id(entity)])
> 
> which stores values in entity_list array. Example: [1, 324232131, 50] so whenever you call entity you need to specify what exactly do you want to take from the list (index, entity address, class id).
> 
> entity[2] means that you want to compare your value to class id stored in an array.

THANKS!
