### ISSUE TITLE
seems to be very buggy at the moment

### ISSUE THREAD

**Issue by cupiditys** [OpsecGuy/BetterGo#16]
trying to open immediately crashes with `"unsupported operand type(s) for +=: 'NoneType' and 'int'"`, commenting out Cmd_ExecuteCommand in offsets stops the immediate crash but eventually will crash game anyways after like 15 minutes with error `Could not write memory at: 1628962520, length: b'\xfe\xff\xff\xff\xc0\xc0\xbdm\xf9\xf8\xf8>\xc1\xc0@=\xcd\xccL>\xfc\xfb{?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80?\x8f\xc7\xc02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff' - GetLastError: 5` (glow esp)

or maybe its just a me problem

**Comment by OpsecGuy** [comment]
Issue has been fixed. Use the latest version.
