### ISSUE TITLE
the overlay is not working

### ISSUE THREAD

**Issue by riviello444** [OpsecGuy/BetterGo#20]
every ov future isnt working

**Comment by OpsecGuy** [comment]
Hello @riviello444,
Please make sure your game is running with Full Screen Windowed Mode.

**Comment by riviello444** [comment]
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
Threads have been canceled! Exiting...
Reason: name 'ov' is not defined
Exiting...

**Comment by riviello444** [comment]
it is running in the full screen mode, the problem is in the source or with the lib

**Comment by OpsecGuy** [comment]
# #https://github.com/OpsecGuy/BetterGo/issues/21

**Comment by MattPlayGamez** [comment]
@riviello444 if it worked. plz close the issue

**Comment by riviello444** [comment]
well it is still **not working**, even after the update if i want to enable it, nothing happens. please try to fix itr in your free time, maybe it is up to some things that arent on my pc and they are on urs.
