### ISSUE TITLE
problem when I try to run the cheat. 

### ISSUE THREAD

**Issue by ImnewtothisL** [OpsecGuy/BetterGo#21]
This was already mentioned on the UC thread by PczWare

![Screenshot 2023-03-04 230144](https://user-images.githubusercontent.com/75602290/222924094-8f7d4566-88bb-4c17-b6b2-684a60ae2144.png)

https://imgur.com/xMiYXbn

Might as well put it here bc its also happening to me but it might be me doing something wrong.

**Comment by OpsecGuy** [comment]
Hello,

Thank you for reporting this issue and I provide here solution for that.
My program is using 3rd party libraries like OpenGL GLUT, which causes all that problems.
Fix for it is quite simple and here are steps that needs to be done in case to make everything working correctly.

1. Check what python versions are installed on your PC and make sure you using at least python 3.8+
[FOR PYTHON 3.11]
2. Download PyOpenGL_accelerate‑3.1.6‑cp311‑cp311‑win_amd64.whl and PyOpenGL‑3.1.6‑cp311‑cp311‑win_amd64.whl
3. Go to CMD and run this commands:
pip install PyOpenGL-3.1.6-cp311-cp311-win_amd64.whl --force-reinstall
pip install PyOpenGL_accelerate‑3.1.6‑cp311‑cp311‑win_amd64.whl

Once you do it you can run my program and everything should work correctly.

**Comment by ImnewtothisL** [comment]
> 

Thank you so much!

**Comment by ImnewtothisL** [comment]
⁹
