### ISSUE TITLE
Overlay not aligning properly

### ISSUE THREAD

**Issue by MattPlayGamez** [OpsecGuy/BetterGo#23]
Dear,
The overlay isn't aligning properly it is a minor issue.
![image](https://user-images.githubusercontent.com/62027538/224477333-ccc37c1c-726a-4312-b87c-64b7a147c279.png)

**Comment by OpsecGuy** [comment]
Do you run game in full screen windowed mode?

**Comment by OpsecGuy** [comment]
@MattPlayGamez do you have any updates?

**Comment by MattPlayGamez** [comment]
Yes,
I've thé same issue in fullscreen

Op wo 15 mrt. 2023 22:02 schreef OpsecGuy ***@***.***>:

**Comment by OpsecGuy** [comment]
https://github.com/OpsecGuy/BetterGo/issues/33#issuecomment-1528166476
