### ISSUE TITLE
Question about player health

### ISSUE THREAD

**Issue by LDzik** [OpsecGuy/BetterGo#25]
Very cool release, I'm using some things from it. Thank you for players names especially.
So here is the thing, I'm getting the player health it's fine when I start the program (everyones health is correct), but when the round ends everyone who died in the enemy team will have their health set to 0 until it gets updated, how can I make it so that maybe there is a check if one of my team health is back to 100 everyone health is set to 100, I guess it is just visual thing because as I said when enemy player gets hit the health updates properly. sorry for bad eng

**Comment by OpsecGuy** [comment]
Hey,
At first I'm glad to see you like my project <3, but let's back to your issue.
In general CS:GO (It's engine) limits reading data from players if they are dormant, which seems to be your issue so you definitely should use that as a check before performing any actions in your code.

I am not really sure how your code looks, but to not spam this repo of people with problems just invite me on discord and we will see what's the problem.
Opsec#3709

**Comment by LDzik** [comment]
ah yes thats probably the issue thx for help
