### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by RenaFor01** [OpsecGuy/BetterGo#27]
Hello, this issue was reported on UC by this guy, I'm having the same issue, I've compiled it into an exe and even before that it wasn't working. I'm not getting any error and I'm using windowed fullscreen.
Any idea on how to fix this? thanks!

![Captura de ecrã 2023-03-20 185029](https://user-images.githubusercontent.com/91011776/226437970-93b4500e-2efc-4bae-94cd-41e66313d453.png)

**Comment by OpsecGuy** [comment]
https://github.com/OpsecGuy/BetterGo/issues/33#issuecomment-1528166476
