### ISSUE TITLE
Offsets are outdated.

### ISSUE THREAD

**Issue by tedzify** [OpsecGuy/BetterGo#39]
Most of the safe/legit functions fails to work, at least on my experience. I have just tried using the program today. Note that I have all the requirements installed such as: `Python 11`, `pip install PyOpenGL_accelerate‑3.1.6‑cp311‑cp311‑win_amd64.whl` and `PyOpenGL-3.1.6-cp311-cp311-win_amd64`. However, most of the functions aren't working, here are the functions that I tested and are NOT working:

- RCS
- Triggerbot
- Everything on the overlay tab except `Grenade Trajectory`
- Auto pistol
- Auto Zeus
- Knife bot

Yes I am running the game on 'Fullscreen Windowed'. RCS doesn't seem to work regardless of how much I mess with the slider. Triggerbot does not fire the gun at all. Nothing is visible on the most of the overlay tab. I tried changing the hotkey for the auto pistol and it does not work. For auto zeus and knife bot, going near the enemies does not seem to work, or at least from what I understood that is how it's supposed to work. I even tried to see the difference with `Safe Mode` enabled and disabled but it doesn't seem to fix the issues. So, is the issue on my side or are the offsets outdated?

Edit: Yes, offsets are outdated.

**Comment by Pczinho** [comment]
Update the offsets 
https://github.com/frk1/hazedumper

**Comment by tedzify** [comment]
Yes the offsets are outdated. Not complaining but the responsibility of updating the offsets shouldn't be on the user. If the project owner wants us to update the offsets ourselves, at least provide instructions to do so.

**Comment by OpsecGuy** [comment]
Hello,
Program is working fine even after long time of not updating it.
https://i.imgur.com/wLOJy6C.jpeg

From what you said I can think only about issue that occur when PyOpenGL packages are not installed properly.
Some features are using overlay and if overlay is not working for you properly, they ain't work too.
Please make sure that files have been installed and if so reinstall them with --force-reinstall flag <-- Check out FAQ
