### ISSUE TITLE
Trust Factor issues

### ISSUE THREAD

**Issue by Okie12345** [OpsecGuy/BetterGo#42]
I downloaded compiled version from unknowncheats and even without using flagged functions i get red trust

**Comment by Okie12345** [comment]
it can be grenade trajectory, you should flag it

**Comment by Okie12345** [comment]
Update: grenade trajectory is definetely (90% sure) lowering trust factor, please flag it

**Comment by OpsecGuy** [comment]
A few more features has been protected with safe mode in newest update.
