### ISSUE TITLE
not a issue but huge vouch for this cheat its so ud, ive been raging in comp hard raging for 6 hours no ban and still going

### ISSUE THREAD

**Issue by Imahaa** [OpsecGuy/BetterGo#5]
![image](https://user-images.githubusercontent.com/107617784/183918401-e0a15ad7-10f8-4af9-a0f1-eef320600b6b.png)

**Comment by OpsecGuy** [comment]
Be careful of overwatch bans. They seems to be more active recently.

**Comment by Imahaa** [comment]
> Be careful of overwatch bans. They seems to be more active recently.

been two days no sign of a ban, im wallbanging full raging now
